export const API_OVERVIEW_URL = 'http://localhost:8080/api/time/all'
export const API_DIFF_URL = 'http://localhost:8080/api/time/diff'
export const API_REGISTER_URL = 'http://localhost:8080/api/user/register'
export const API_LOGIN_URL = 'http://localhost:8080/api/user/login'
export const API_POST_TIME_URL = 'http://localhost:8080/api/time'
export const API_GET_LATEST_TIME_URL = 'http://localhost:8080/api/time'
export const API_PUT_TIME_URL = 'http://localhost:8080/api/time/endtime'